api:
    resource: "@APIBundle/Controller/"
    type:     annotation
    prefix:   /api

app:
    resource: "@AppBundle/Resources/config/routing.yml"

app_admin:
    prefix: /admin
    resource: "@AppBundle/Resources/config/routing_admin.yml"