services:
    api.view_response_listener:
        class: APIBundle\EventListener\ViewResponseListener
        tags:
            - {name: kernel.event_subscriber}

    api.exception_listener:
        class: APIBundle\EventListener\ExceptionListener
        tags:
            - {name: kernel.event_subscriber}