homepage:
  path:      /
  defaults:  { _controller: AppBundle:Example:homepage }

login:
  path:      /login
  defaults:  { _controller: AppBundle:Example:login }

login_check:
  path:      /login_check
  defaults:  { _controller: AppBundle:Example:loginCheck }

logout:
  path:      /logout
  defaults:  { _controller: AppBundle:Example:logout }

register:
  path:      /register
  defaults:  { _controller: AppBundle:Example:register }

example_form_submit:
  path:      /example/form_submit
  defaults:  { _controller: AppBundle:Example:formSubmit }

example_ajax_form_submit:
  path:      /example/ajax_form_submit
  defaults:  { _controller: AppBundle:Example:ajaxFormSubmit }

